managed_identity_object_id = "4ed764fd-4355-4904-a460-eead84caac63"
TF_STATE_STORAGE_TEMPLATE = "statestore"
STORE_sa_name_template = "statestore"
TF_STATE_CONTAINER_TEMPLATE = "statectr"
STORE_sa_container_name_template = "statectr"
